### ISSUE TITLE
how to compare the qemuafl with clean qemu

### ISSUE THREAD

**Issue by Frankenstein-bit** [AFLplusplus/qemuafl#19]
i want to see what has been changed in qemuafl compare with a clean,so that i can easily get how qemuafl work
can you help me?

**Comment by vanhauser-thc** [comment]
simply compare to to upstream to the commit id that was last pulled here: https://github.com/AFLplusplus/qemuafl/commits/master

**Comment by Frankenstein-bit** [comment]
> simply compare to to upstream to the commit id that was last pulled here: https://github.com/AFLplusplus/qemuafl/commits/master

may be i did not express myself clearly,
for example,i want to know what has been changed in this qemuafl（ here is 
 the link i am instreasted :https://github.com/AFLplusplus/qemuafl/tree/21ff34383764a8c6f66509b3b8d5282468c721e1）compare with a clean qemu.
