### ISSUE TITLE
ASAN_GIOVESE breaks non-x86, non-ARM builds

### ISSUE THREAD

**Issue by MarkEmerus** [AFLplusplus/qemuafl#24]
In qemuafl/qasan-qemu.h on line 94 is the statement `#error "Target not supported by asan-giovese"` This is an issue because any non-x86, non-ARM architecture will trigger this statement due to ASAN_GIOVESE being unconditionally defined on line 29. Based on the else block that starts on line 97 it seems this is not the intended design. Instead, ASAN_GIOVESE should probably be defined conditionally based on the value of an environment variable.

However, even that is not a complete fix. When I comment out line 29 there is a linking error in the build process related to calls to the functions starting on line 99. Based on a quick look I couldn’t determine why linking failed.

**Comment by andreafioraldi** [comment]
It compiles with PPC as a target now.
