### ISSUE TITLE
Vague error message when dlopen QEMU_PERSISTENT_HOOK fails

### ISSUE THREAD

**Issue by dlmarrero** [AFLplusplus/qemuafl#43]
The error message displayed when `dlopen` fails to load `QEMU_PERSISTENT_HOOK` does not describe why the failure occurred. Printing the output from [dlerror](https://linux.die.net/man/3/dlerror) would make troubleshooting much easier. I can submit a PR if the maintainers agree.

https://github.com/AFLplusplus/qemuafl/blob/fa07ebfff5de3d7a531caf2f9e0306960953a5e7/accel/tcg/cpu-exec.c#L517-L524

**Comment by vanhauser-thc** [comment]
sure, send a PR :)
