### ISSUE TITLE
Support for UNICORN-like hooking

### ISSUE THREAD

**Issue by CowBoy4mH3LL** [AFLplusplus/qemuafl#58]
I was wondering if QEMUAFL is considering a UNICORN-like hooking framework built into QEMUAFL?

This would greatly reduce runtime overheads of UNICORN/QILING.
Also, it could leverage the sanitisation, persistence, selective instrumentation, etc. methods that come with QEMUAFL, as opposed the "catch your own bug" method of the pythonic alternatives. 

Any thoughts?

**Comment by vanhauser-thc** [comment]
Not sure how this would work but send a PR :)

**Comment by CowBoy4mH3LL** [comment]
Coming soon then :)
